name: Build and test React app
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 19.x
      - name: Run component tests
        uses: cypress-io/github-action@v5.1.0
        with:
          install-command: npm install --force
          start: npm start
          command: npm run test:comp
      - name: Run integration tests (Chrome)
        uses: cypress-io/github-action@v5.1.0
        with:
          start: npm start
          browser: chrome
          wait-on: 'http://localhost:3000'
          command: npm run test:int

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render with webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          method: 'GET'
