name: Deploy to Production Server
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render with webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          method: 'GET'
