name: Deploy to Production Server
on:
  workflow_run:
    workflows: ['Build and test React app']
    branches:
      - 'main'
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render with webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          method: 'GET'
